services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    # setup environment variables to enable AOF and RDB persistence
    environment:
      - REDIS_AOF_ENABLED=yes
      - REDIS_RDB_ENABLED=yes
      - REDIS_AOF_FILE_SIZE=1mb
      - REDIS_AOF_FILE_COUNT=2
      - REDIS_RDB_COMPRESSION=yes
      - REDIS_RDB_FILE_NAME=redis.rdb
      - REDIS_RDB_FILE_COMPRESSION=yes
      - REDIS_RDB_FILE_COMPRESSION_LEVEL=9
      - REDIS_RDB_FILE_COMPRESSION_TYPE=gzip
